server:
  port: 8082
  
spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: Reportes Marcos Tonda
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
      
logging:
  level:
    org:
      hibernate:
        SQL: debug
 
---
spring:
  profiles: devw
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
    url: jdbc:h2:file:E:/desarrollo/auto-estudio/reportes
    username: sa
    password:

---
spring:
  profiles: dev
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5433/reporte-almacen
    username: postgres
    password: root

---
spring:
  profiles: pro
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/reportespg
    username: reportespg
    password: reportespg