INSERT INTO USUARIO(USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES('gapolo', 'George', 'Apolo', 'grapoloutpl@gmail.com', '$2a$04$n6WIRDQlIByVFi.5rtQwEOTAzpzLPzIIG/O6quaxRKY2LlIHG8uty');
INSERT INTO USUARIO(USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES('scabrera', 'Santiago', 'Cabrera', 'santiago.cabrera.murillo@gmail.com', '$2a$04$n6WIRDQlIByVFi.5rtQwEOTAzpzLPzIIG/O6quaxRKY2LlIHG8uty');

INSERT INTO ROL(DESCRIPTION, NAME) VALUES ('ROLE_ADMIN', 'ADMIN');
INSERT INTO ROL(DESCRIPTION, NAME) VALUES ('ROLE_USER', 'USER');
INSERT INTO ROL(DESCRIPTION, NAME) VALUES ('ROLE_SUPERVISOR', 'SUPERVISOR');

INSERT INTO USUARIO_ROLES(USUARIO_ID, ROL_ID) VALUES(1, 1);
INSERT INTO USUARIO_ROLES(USUARIO_ID, ROL_ID) VALUES(2, 1);