DROP TABLE IF EXISTS ROL;
CREATE TABLE ROL(
    ID          INT             AUTO_INCREMENT  PRIMARY KEY,
    NAME        VARCHAR(30)     NOT NULL,
    DESCRIPTION VARCHAR(250)    NOT NULL
);

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
    ID          INT             AUTO_INCREMENT  PRIMARY KEY,
    FIRST_NAME  VARCHAR(20)     NOT NULL,
    LAST_NAME   VARCHAR(20)     NOT NULL,
    EMAIL       VARCHAR(30)     NOT NULL,
    USERNAME    VARCHAR(10)     NOT NULL,
    PASSWORD    VARCHAR(300)    NOT NULL
);

DROP TABLE IF EXISTS USUARIO_ROLES;
CREATE TABLE USUARIO_ROLES(       
    USUARIO_ID  INT     NOT NULL,
    ROL_ID	INT	NOT NULL 
);

DROP TABLE IF EXISTS ACTIVIDAD;
CREATE TABLE ACTIVIDAD(
	ID						INTEGER			AUTO_INCREMENT  PRIMARY KEY,
	CLIENTE					VARCHAR(255),
	COBRO					INTEGER			NOT NOT,
	ELABORADO_POR			VARCHAR(255)
	FECHA_CREACION			TIME			NOT NULL,
	HORA_ENTRADA_MANANA		TIME			NOT NULL,
	HORA_ENTRADA_TARDE		TIME			NOT NULL,
	HORA_SALIDA_MANANA		TIME			NOT NULL,
	HORA_SALIDA_TARDE		TIME			NOT NULL,
	INCIDENCIA				VARCHAR(255),
	OTROS					VARCHAR(255),
	PEDIDO					INTEGER			NOT NULL,
	POBLACION				VARCHAR(255),
	TIPO					VARCHAR(255),
	VISITA					INTEGER			NOT NULL
);


-- POSTGRES

-- SECUENCIAS
DROP SEQUENCE ROL_ID_SEQ;
DROP SEQUENCE USUARIO_ID_SEQ;
CREATE SEQUENCE ROL_ID_SEQ;
CREATE SEQUENCE USUARIO_ID_SEQ;
CREATE SEQUENCE VISITA_ID_SEQ;


-- TABLA: ROL
DROP TABLE IF EXISTS ROL;
CREATE TABLE ROL(
    ID       	INT		DEFAULT NEXTVAL('ROL_ID_SEQ')	PRIMARY KEY	NOT NULL,
    NAME        TEXT                                				NOT NULL,
    DESCRIPTION TEXT                                				NOT NULL
);

-- TABLA: USUARIO
DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
    ID	        INT		DEFAULT NEXTVAL('USUARIO_ID_SEQ')	PRIMARY KEY	NOT NULL,
    FIRST_NAME  TEXT    												NOT NULL,
    LAST_NAME   TEXT                                					NOT NULL,
    EMAIL       TEXT                                					NOT NULL,
    USERNAME    TEXT                                					NOT NULL,
    PASSWORD    TEXT                                					NOT NULL
);

-- TABLA: USUARIO_ROLES
DROP TABLE IF EXISTS USUARIO_ROLES;
CREATE TABLE USUARIO_ROLES(       
    USUARIO_ID	INT		NOT NULL,
    ROL_ID		INT		NOT NULL 
);

DROP TABLE IF EXISTS ACTIVIDAD;
CREATE TABLE ACTIVIDAD(
	ID	        			INT		DEFAULT NEXTVAL('ACTIVIDAD_ID_SEQ')	PRIMARY KEY	NOT NULL,
	CLIENTE					TEXT,
	COBRO					INT														NOT NULL,
	ELABORADO_POR			TEXT,
	FECHA_CREACION			TIME													NOT NULL,
	HORA_ENTRADA_MANANA		TIME													NOT NULL,
	HORA_ENTRADA_TARDE		TIME													NOT NULL,
	HORA_SALIDA_MANANA		TIME													NOT NULL,
	HORA_SALIDA_TARDE		TIME													NOT NULL,
	INCIDENCIA				TEXT,
	OTROS					TEXT,
	PEDIDO					INT														NOT NULL,
	POBLACION				TEXT,
	TIPO					TEXT,
	VISITA					INT														NOT NULL
);
*/