-- SECUENCIAS
DROP SEQUENCE IF EXISTS ROL_ID_SEQ;
DROP SEQUENCE IF EXISTS USUARIO_ID_SEQ;
DROP SEQUENCE IF EXISTS VISITA_ID_SEQ;
DROP SEQUENCE IF EXISTS ACTIVIDAD_ID_SEQ;
DROP SEQUENCE IF EXISTS REPORTE_ID_SEQ;
DROP SEQUENCE IF EXISTS REPORTE_ACTIVIDAD_ID_SEQ;
DROP SEQUENCE IF EXISTS REPORTE_ALMACEN_ID_SEQ;
DROP SEQUENCE IF EXISTS ACTIVIDAD_COMERCIAL_ID_SEQ;

CREATE SEQUENCE ROL_ID_SEQ;
CREATE SEQUENCE USUARIO_ID_SEQ;
CREATE SEQUENCE VISITA_ID_SEQ;
CREATE SEQUENCE ACTIVIDAD_ID_SEQ;
CREATE SEQUENCE REPORTE_ID_SEQ;
CREATE SEQUENCE REPORTE_ACTIVIDAD_ID_SEQ;
CREATE SEQUENCE REPORTE_ALMACEN_ID_SEQ;
CREATE SEQUENCE ACTIVIDAD_COMERCIAL_ID_SEQ;

-- H2s
DROP TABLE IF EXISTS ROL;
CREATE TABLE ROL(
    ID       	INT		DEFAULT NEXTVAL('ROL_ID_SEQ')	PRIMARY KEY	NOT NULL,
    NAME        VARCHAR(30)     NOT NULL,
    DESCRIPTION VARCHAR(250)    NOT NULL
);

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
    ID	        INT		DEFAULT NEXTVAL('USUARIO_ID_SEQ')	PRIMARY KEY	NOT NULL,
    FIRST_NAME  VARCHAR(20),
    LAST_NAME   VARCHAR(20),
    EMAIL       VARCHAR(50),
    USERNAME    VARCHAR(10),
    PASSWORD    VARCHAR(300)
);

DROP TABLE IF EXISTS USUARIO_ROLES;
CREATE TABLE USUARIO_ROLES(       
    USUARIO_ID  INT     NOT NULL,
    ROL_ID	INT	NOT NULL 
);

DROP TABLE IF EXISTS ACTIVIDAD;
CREATE TABLE ACTIVIDAD(
	ID	        		INT		DEFAULT NEXTVAL('ACTIVIDAD_ID_SEQ')	PRIMARY KEY	NOT NULL,
	CLIENTE				VARCHAR(255),
	COBRO				INT,
	ELABORADO_POR			VARCHAR(255),
	FECHA_CREACION			TIMESTAMP,
	HORA_ENTRADA			TIMESTAMP,
	HORA_SALIDA			TIMESTAMP,
	HORA_ENTRADA_MANANA		TIMESTAMP,
	HORA_ENTRADA_TARDE		TIMESTAMP,
	HORA_SALIDA_MANANA		TIMESTAMP,
	HORA_SALIDA_TARDE		TIMESTAMP,
	INCIDENCIAS			VARCHAR(255),
	OTROS				VARCHAR(255),
	PEDIDO				INT,
	PROVEEDORES			INT,
	REPARTOS			INT,
	POBLACION			VARCHAR(255),
	OBSERVACIONES			VARCHAR(255),
	VISITA				INT,
	TIPO				TEXT
);

DROP TABLE IF EXISTS REPORTE;
CREATE TABLE REPORTE(
	ID				INT		DEFAULT NEXTVAL('REPORTE_ID_SEQ')	PRIMARY KEY	NOT NULL,
	NUMERO				VARCHAR(255),
	ELABORADO_POR			VARCHAR(255),
	FECHA_DESDE			TIMESTAMP,
	FECHA_HASTA			TIMESTAMP,
	FECHA_CREACION			TIMESTAMP,
	TIPO				VARCHAR(255)
);

DROP TABLE IF EXISTS REPORTE_ALMACEN;
CREATE TABLE REPORTE_ALMACEN(
	ID			INT		DEFAULT NEXTVAL('REPORTE_ALMACEN_ID_SEQ')	PRIMARY KEY	NOT NULL,
	NUMERO			VARCHAR(255),
	REVISADO_POR		VARCHAR(255),
	ELABORADO_POR		VARCHAR(255),
	FECHA_CREACION		TIMESTAMP,
	HORA_ENTRADA		TIMESTAMP,
	HORA_SALIDA		TIMESTAMP,
	FRANK			INT,
	VICENTE			INT,
	INTEGRA			INT,
	GEORGE			INT,
	BLUE			INT,
	OTROS			INT,
	PROVEEDORES_DESCARGADOS	INT,
	REPARTOS_GEORGE		INT,
	OBSERVACIONES		VARCHAR(500),
	INCIDENCIAS		VARCHAR(500)
);

DROP TABLE IF EXISTS REPORTE_ACTIVIDAD;
CREATE TABLE REPORTE_ACTIVIDAD(
	ID_REPORTE_ACTIVIDAD	INT	DEFAULT NEXTVAL('REPORTE_ACTIVIDAD_ID_SEQ')	PRIMARY KEY	NOT NULL,
	ID_REPORTE		INT,
	ID_ACTIVIDAD		INT
);

-- TABLA: ACTIVIDAD_COMERCIAL
DROP TABLE IF EXISTS ACTIVIDAD_COMERCIAL;
CREATE TABLE ACTIVIDAD_COMERCIAL(
	ID				INT		DEFAULT NEXTVAL('ACTIVIDAD_COMERCIAL_ID_SEQ')	PRIMARY KEY	NOT NULL,
	REVISADO_POR			VARCHAR(200),
	ELABORADO_POR			VARCHAR(200),
	FECHA_CREACION			TIMESTAMP,
	HORA_ENTRADA			TIMESTAMP,
	HORA_SALIDA			TIMESTAMP,
	NOMBRE				VARCHAR(200),
	POBLACION			VARCHAR(200),
	REPARTO				VARCHAR(10),
	COBRO				VARCHAR(10),
	PEDIDO				VARCHAR(10),
	OBSERVACIONES			VARCHAR(500),
	INCIDENCIAS			VARCHAR(500)
);


/*
-- POSTGRES

-- TABLA: ROL
DROP TABLE IF EXISTS ROL;
CREATE TABLE ROL(
    ID       	INT		DEFAULT NEXTVAL('ROL_ID_SEQ')	PRIMARY KEY	NOT NULL,
    NAME        TEXT                                				NOT NULL,
    DESCRIPTION TEXT                                				NOT NULL
);

-- TABLA: USUARIO
DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
    ID	        INT	DEFAULT NEXTVAL('USUARIO_ID_SEQ')	PRIMARY KEY	NOT NULL,
    FIRST_NAME  TEXT    												NOT NULL,
    LAST_NAME   TEXT,
    EMAIL       TEXT,
    USERNAME    TEXT,
    PASSWORD    TEXT
);

-- TABLA: USUARIO_ROLES
DROP TABLE IF EXISTS USUARIO_ROLES;
CREATE TABLE USUARIO_ROLES(       
    USUARIO_ID	INT	NOT NULL,
    ROL_ID	INT	NOT NULL 
);

-- TABLA: ACTIVIDAD
DROP TABLE IF EXISTS ACTIVIDAD;
CREATE TABLE ACTIVIDAD(
	ID	        		INT		DEFAULT NEXTVAL('ACTIVIDAD_ID_SEQ')	PRIMARY KEY	NOT NULL,
	CLIENTE				TEXT,
	COBRO				INT,
	ELABORADO_POR			TEXT,
	FECHA_CREACION			TIME,
	HORA_ENTRADA			TIME,
	HORA_SALIDA			TIME,
	HORA_ENTRADA_MANANA		TIME,
	HORA_ENTRADA_TARDE		TIME,
	HORA_SALIDA_MANANA		TIME,
	HORA_SALIDA_TARDE		TIME,
	INCIDENCIAS			TEXT,
	OTROS				TEXT,
	PEDIDO				INT,
	PROVEEDORES			INT,
	REPARTOS			INT,
	POBLACION			TEXT,
	OBSERVACIONES			TEXT,
	VISITA				INT,
	TIPO				TEXT
);

-- TABLA: REPORTE
DROP TABLE IF EXISTS REPORTE;
CREATE TABLE REPORTE(
	ID				INT	DEFAULT NEXTVAL('REPORTE_ID_SEQ')	PRIMARY KEY	NOT NULL,
	NUMERO				TEXT,
	ELABORADO_POR			TEXT,
	FECHA_DESDE			TIME,
	FECHA_HASTA			TIME,
	FECHA_CREACION			TIME,
	TIPO				TEXT
);

-- TABLA: REPORTE_ALMACEN
DROP TABLE IF EXISTS REPORTE_ALMACEN;
CREATE TABLE REPORTE_ALMACEN(
	ID			INT		DEFAULT NEXTVAL('REPORTE_ALMACEN_ID_SEQ')	PRIMARY KEY	NOT NULL,
	NUMERO			TEXT,
	REVISADO_POR		TEXT,
	ELABORADO_POR		TEXT,
	FECHA_CREACION		TIMESTAMP,
	HORA_ENTRADA		TIME,
	HORA_SALIDA		TIME,
	FRANK			INT,
	VICENTE			INT,
	INTEGRA			INT,
	GEORGE			INT,
	BLUE			INT,
	OTROS			INT,
	PROVEEDORES_DESCARGADOS	INT,
	REPARTOS_GEORGE		INT,
	OBSERVACIONES		TEXT,
	INCIDENCIAS		TEXT
);

-- TABLA: REPORTE_ACTIVIDAD
DROP TABLE IF EXISTS REPORTE_ACTIVIDAD;
CREATE TABLE REPORTE_ACTIVIDAD(
	ID_REPORTE_ACTIVIDAD	INT		DEFAULT NEXTVAL('REPORTE_ACTIVIDAD_ID_SEQ')	PRIMARY KEY	NOT NULL,
	ID_REPORTE		INT,
	ID_ACTIVIDAD		INT
);

-- TABLA: ACTIVIDAD_COMERCIAL
DROP TABLE IF EXISTS ACTIVIDAD_COMERCIAL;
CREATE TABLE ACTIVIDAD_COMERCIAL(
	ID						INT		DEFAULT NEXTVAL('ACTIVIDAD_COMERCIAL_ID_SEQ')	PRIMARY KEY	NOT NULL,
	REVISADO_POR			TEXT,
	ELABORADO_POR			TEXT,
	FECHA_CREACION			TIMESTAMP,
	HORA_ENTRADA			TIME,
	HORA_SALIDA			TIME,
	NOMBRE				TEXT,
	POBLACION			TEXT,
	REPARTO				TEXT,
	COBRO				TEXT,
	PEDIDO				TEXT,
	OBSERVACIONES			TEXT,
	INCIDENCIAS			TEXT
);
*/