-- SECUENCIAS
CREATE SEQUENCE ROL_ID_SEQ;
CREATE SEQUENCE USUARIO_ID_SEQ;


-- TABLA: ROL
CREATE TABLE ROL(
    ID       	INT		DEFAULT NEXTVAL('ROL_ID_SEQ')	PRIMARY KEY	NOT NULL,
    NAME        TEXT                                				NOT NULL,
    DESCRIPTION TEXT                                				NOT NULL
);

CREATE TABLE USUARIO(
	ID			INT		DEFAULT NEXTVAL('USUARIO_ID_SEQ')	PRIMARY KEY	NOT NULL,
    FIRST_NAME  TEXT    												NOT NULL,
    LAST_NAME   TEXT                                					NOT NULL,
    EMAIL       TEXT                                					NOT NULL,
    USERNAME    TEXT                                					NOT NULL,
    PASSWORD    TEXT                                					NOT NULL
);

CREATE TABLE USUARIO_ROLES(       
    USUARIO_ID	INT		NOT NULL,
    ROL_ID		INT		NOT NULL 
);                                

-- INSERT
INSERT INTO USUARIO (EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME) VALUES ('admin@admin.com', 'admin', 'admin', '12345', 'admin');

INSERT INTO ROL (DESCRIPTION, NAME) VALUES ('ROLE_ADMIN', 'ADMIN');
INSERT INTO ROL (DESCRIPTION, NAME) VALUES ('ROLE_USER', 'USER');
INSERT INTO ROL (DESCRIPTION, NAME) VALUES ('ROLE_SUPERVISOR', 'SUPERVISOR');

INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL_ID) VALUES ('1', '1');




SELECT * FROM USUARIO;
SELECT * FROM ROL;
SELECT * FROM USUARIO_ROLES;

UPDATE USUARIO SET PASSWORD = '$2a$04$/ziyQDLsLLPnhjR.Xb.UO.8hlPzXEWGmsyBrFpM/9W1U5kxAJmSVW' WHERE USERNAME = 'admin';
UPDATE USUARIO_ROLES SET USUARIO_ID = 4, ROL_ID = 8 WHERE USUARIO_ID = 1 AND ROL_ID = 1;