SELECT * FROM USUARIO;
SELECT * FROM ROL;
SELECT * FROM USUARIO_ROLES;

UPDATE USUARIO SET PASSWORD = '$2a$04$/ziyQDLsLLPnhjR.Xb.UO.8hlPzXEWGmsyBrFpM/9W1U5kxAJmSVW' WHERE USERNAME = 'admin';
UPDATE USUARIO_ROLES SET USUARIO_ID = 4, ROL_ID = 8 WHERE USUARIO_ID = 1 AND ROL_ID = 1;



INSERT INTO USUARIO(ID, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES(1, 'gapolo', 'George', 'Apolo', 'grapoloutpl@gmail.com', '$2a$04$n6WIRDQlIByVFi.5rtQwEOTAzpzLPzIIG/O6quaxRKY2LlIHG8uty');
INSERT INTO USUARIO(ID, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES(2, 'scabrera', 'Santiago', 'Cabrera', 'santiago.cabrera.murillo@gmail.com', '$2a$04$n6WIRDQlIByVFi.5rtQwEOTAzpzLPzIIG/O6quaxRKY2LlIHG8uty');

INSERT INTO ROL(ID, DESCRIPTION, NAME) VALUES (1, 'ROLE_ADMIN', 'ADMIN');
INSERT INTO ROL(ID, DESCRIPTION, NAME) VALUES (2, 'ROLE_USER', 'USER');
INSERT INTO ROL(ID, DESCRIPTION, NAME) VALUES (3, 'ROLE_SUPERVISOR', 'SUPERVISOR');

INSERT INTO USUARIO_ROLES(USUARIO_ID, ROL_ID) VALUES(1, 1);
INSERT INTO USUARIO_ROLES(USUARIO_ID, ROL_ID) VALUES(2, 1);