SELECT * FROM USUARIO;
SELECT * FROM ROL;
SELECT * FROM USUARIO_ROLES;

UPDATE USUARIO SET PASSWORD = '$2a$04$/ziyQDLsLLPnhjR.Xb.UO.8hlPzXEWGmsyBrFpM/9W1U5kxAJmSVW' WHERE USERNAME = 'admin';
UPDATE USUARIO_ROLES SET USUARIO_ID = 4, ROL_ID = 8 WHERE USUARIO_ID = 1 AND ROL_ID = 1;